package_assets: on
gzip_assets: off

javascripts:
  game:
    - 'public/javascripts/jquery.js'
    - 'public/javascripts/jquery-ui/js/jquery-ui-1.8.9.custom.min.js'
    - 'public/javascripts/jquery.mousewheel.min.js'
    - 'public/javascripts/jquery.countdown.min.js'
    - 'public/javascripts/jquery.jcarousel.min.js'
    - 'public/javascripts/json2.js'
    - 'public/javascripts/js-class/min/core.js'
    - 'public/javascripts/js-class/min/comparable.js'
    - 'public/javascripts/js-class/min/enumerable.js'
    - 'public/javascripts/js-class/min/hash.js'
    - 'public/javascripts/js-class/min/set.js'
    - 'public/javascripts/js-class/min/state.js'
    - 'public/javascripts/ec/engine/dialog.js'
    - 'public/javascripts/ec/game/login_dialog.js'
    - 'public/javascripts/ec/game/confirmation_dialog.js'
    - 'public/javascripts/ec/engine/core_ext.js'
    - 'public/javascripts/ec/engine/h_coordinate.js'
    - 'public/javascripts/ec/engine/map.js'
    - 'public/javascripts/ec/engine/path_finder.js'
    - 'public/javascripts/ec/engine/range_finder.js'
    - 'public/javascripts/ec/engine/sprite_sheet.js'
    - 'public/javascripts/ec/engine/sprite.js'
    - 'public/javascripts/ec/engine/composite_sprite.js'
    - 'public/javascripts/ec/game/sprite_sheets.js'
    - 'public/javascripts/ec/game/unit.js'
    - 'public/javascripts/ec/game/base.js'
    - 'public/javascripts/ec/game/user.js'
    - 'public/javascripts/ec/game/game.js'
    - 'public/javascripts/ec/game/terrain_modifier.js'
    - 'public/javascripts/ec/game/tm_road_sprite.js'
    - 'public/javascripts/ec/game/tm_bridge_sprite.js'
    - 'public/javascripts/ec/game/tm_plains_sprite.js'
    - 'public/javascripts/ec/game/spcl_interpreter.js'
    - 'public/javascripts/ec/game/game_command.js'
    - 'public/javascripts/ec/game/composite_game_command.js'
    - 'public/javascripts/ec/game/game_commands/move_unit.js'
    - 'public/javascripts/ec/game/game_commands/attack.js'
    - 'public/javascripts/ec/game/game_commands/capture_base.js'
    - 'public/javascripts/ec/game/game_commands/heal_unit.js'
    - 'public/javascripts/ec/game/game_commands/scrap_unit.js'
    - 'public/javascripts/ec/game/game_commands/buy_unit.js'
    - 'public/javascripts/ec/game/game_commands/load_unit.js'
    - 'public/javascripts/ec/game/game_commands/field_heal_unit.js'
    - 'public/javascripts/ec/game/game_commands/begin_building.js'
    - 'public/javascripts/ec/game/game_commands/end_turn.js'
    - 'public/javascripts/ec/game/game_commands/remind_player.js'
    - 'public/javascripts/ec/game/game_commands/skip_player.js'
    - 'public/javascripts/ec/game/game_commands/force_surrender.js'
    - 'public/javascripts/ec/game/attack_dialog.js'
    - 'public/javascripts/ec/game/capture_base_dialog.js'
    - 'public/javascripts/ec/game/build_dialog.js'
    - 'public/javascripts/ec/game/buy_unit_dialog.js'
    - 'public/javascripts/ec/game/unit_stats_dialog.js'
    - 'public/javascripts/ec/game/loaded_units_dialog.js'
    - 'public/javascripts/ec/game/invite_dialog.js'
    - 'public/javascripts/ec/engine/orbited_controller.js'
    - 'public/javascripts/ec/game/chat_log.js'
    - 'public/javascripts/ec/game/user_comet_controller.js'
    - 'public/javascripts/ec/game/game_alerts_menu.js'
    - 'public/javascripts/ec/game/game_controller.js'
    - 'public/javascripts/ec/game/map_editor_controller.js'

stylesheets:
  game:
    - 'public/javascripts/jquery-ui/css/ui-lightness/jquery-ui-1.8.7.custom.css'
    - 'public/stylesheets/application.css'
    - 'public/stylesheets/game.css'
    - 'public/stylesheets/forums.css'
    - 'public/stylesheets/map_editor.css'
    - 'public/stylesheets/signup.css'
    - 'public/stylesheets/carousel_theme/skin.css'
  ie7:
    - 'public/stylesheets/application_ie7.css'
  ie:
    - 'public/stylesheets/application_ie.css'
